export const BIRTHDAYS = [
    {
        nickname: 'Максим МСК',
        name: 'Максим Анатольевич',
        avatar: './images/modal_birthday_avatars/Maxim_MSK.jpg',
        birthday_date: '11-01-1985',
        about: 'Может ну его накуй?! 🤭🤣',
        work: 'Ищу работу! 😅🤷🏻‍♂️',
    },
    {
        nickname: 'tharevckii13',
        name: 'Александр',
        avatar: './images/modal_birthday_avatars/tharevckii13.jpg',
        birthday_date: '13-02-1977',
        about: 'Всё решаемо',
        work: 'Бур р7',
    },
    {
        nickname: 'tomilov170366',
        name: 'Александр',
        avatar: './images/modal_birthday_avatars/tomilov170366.jpg',
        birthday_date: '17-03-1966',
        about: 'прорвёмся!!',
        work: 'водитьль',
    },
    {
        nickname: 'Джамал',
        name: 'так и зовут Джамал',
        avatar: './images/modal_birthday_avatars/Jamal.jpg',
        birthday_date: '23-03-1986',
        about: 'Всегда на позитиве!',
        work: 'Водитель-экспедитор "Автохадом" самые дешёвые цены на запчасти на СКФО',
    },
    {
        nickname: 'Григорий',
        name: 'Григорий Сергеевич',
        avatar: './images/modal_birthday_avatars/Gregory.jpg',
        birthday_date: '01-05-1978',
        about: 'Москва - Воронеж куй догонишь',
        work: '',
    },
    {
        nickname: 'Александр ',
        name: 'Александр ',
        avatar: './images/modal_birthday_avatars/Alexander.jpg',
        birthday_date: '23-06-1985',
        about: '',
        work: 'Аэропорт Домодедово',
    },
    {
        nickname: 'Бот Игорь',
        name: 'Ихарь',
        avatar: './images/modal_birthday_avatars/Bot_Ihar.jpg',
        birthday_date: '01-07-1981',
        about: 'Хули нет, когда да',
        work: 'Лентяй, тунеядец и ваапшчэ...',
    },
    {
        nickname: 'pazdriver',
        name: 'Олег Никитин',
        avatar: './images/modal_birthday_avatars/pazdriver.jpg',
        birthday_date: '09-07-1979',
        about: 'FUCK FUEL ECONOMY',
        work: '',
    },
    {
        nickname: 'Jekki(Msk)',
        name: 'Жека',
        avatar: './images/modal_birthday_avatars/Jekki.jpg',
        birthday_date: '25-07-1969',
        about: 'Походу я самый старый владелец Пацифики🤣',
        work: 'Сервис сложной электроники',
    },
    {
        nickname: 'Алексей',
        name: 'Алексей',
        avatar: './images/modal_birthday_avatars/Alexei.jpg',
        birthday_date: '28-07-1975',
        about: 'хочу к хоббитам)))',
        work: 'электрика и все понемногу',
    },
    {
        nickname: 'Михаил Тамбов',
        name: 'Михаил Викторович',
        avatar: './images/modal_birthday_avatars/Mikhail_Tambov.jpg',
        birthday_date: '29-07-1974',
        about: 'Один за всех и все за... ',
        work: '',
    },
    {
        nickname: 'AlexIR',
        name: 'Алексей',
        avatar: './images/modal_birthday_avatars/AlexIR.jpg',
        birthday_date: '03-08-1982',
        about: 'Не было печали, купила баба порося.',
        work: 'Администрирование Linux систем',
    },
    {
        nickname: 'Виталий Валерьевич CCCP',
        name: 'Виталий или Валерьевич (ЭЛЕКТРОДЕД)',
        avatar: './images/modal_birthday_avatars/Vitaly_Valerievich_USSR.jpg',
        birthday_date: '05-08-1970',
        about: 'Ишо Живой!!',
        work: 'Управленец. Таксопарк.',
    },
    {
        nickname: 'Алексей',
        name: 'Алексей',
        avatar: './images/modal_birthday_avatars/no_avatar.jpg',
        birthday_date: '08-08-1990',
        about: '',
        work: 'Занимаюсь строительством каркасников и знаю про инструмент практически всё',
    },
    {
        nickname: 'Алексей Фролов',
        name: 'Алексей Дед Мороз, Хатабыч',
        avatar: './images/modal_birthday_avatars/Alexey_Frolov.jpg',
        birthday_date: '16-08-1974',
        about: 'Пакую, один раз живём. ',
        work: 'Автокондиционеры,отопление водоснабжение',
    },
    {
        nickname: 'Сергей Ряжск',
        name: 'Сергей Викторович',
        avatar: './images/modal_birthday_avatars/Sergey_Ryazhsk.jpg',
        birthday_date: '21-08-1967',
        about: 'Быть Добру',
        work: 'Такси... Остальное Вы знаете )))',
    },
    {
        nickname: 'Денис Николаевич',
        name: 'Денис Николаевич ',
        avatar: './images/modal_birthday_avatars/no_avatar.jpg',
        birthday_date: '02-09-1985',
        about: 'Анжанер энергитических конструкций',
        work: 'Сам себе дворник, сантехник, электрик, водитель, директор. Тольк',
    },
    {
        nickname: 'snag83',
        name: 'Сергей',
        avatar: './images/modal_birthday_avatars/snag83.jpg',
        birthday_date: '14-09-1983',
        about: 'Не надо печалиться))) ',
        work: 'Сис.админ',
    },
    {
        nickname: 'Константин',
        name: 'Константин Ростов',
        avatar: './images/modal_birthday_avatars/Konstantin.jpg',
        birthday_date: '16-09-1982',
        about: 'За любой кипишь',
        work: 'Авторемонт',
    },
    {
        nickname: 'Александр Капанжа',
        name: 'Так же и звать)))',
        avatar: './images/modal_birthday_avatars/Alexander_Kapanzha.jpg',
        birthday_date: '12-10-1980',
        about: 'Типа мяломан )))',
        work: 'Кадастровый инженер. Если нужна консультация по оформлению недвижимости: чем смогу - помогу ))',
    },
    {
        nickname: 'Сергей Минск',
        name: 'Сергей',
        avatar: './images/modal_birthday_avatars/Sergey_Minsk.jpg',
        birthday_date: '03-11-1980',
        about: '',
        work: '',
    },
    {
        nickname: 'Сергей Киселев',
        name: 'Караганда',
        avatar: './images/modal_birthday_avatars/Sergey_Kiselev.jpg',
        birthday_date: '17-11-1972',
        about: '',
        work: 'Химчистка одежды, Ковров. Директор ',
    },
    {
        nickname: 'Димон31',
        name: 'Дмитрий Григорьевич',
        avatar: './images/modal_birthday_avatars/Dimon31.jpg',
        birthday_date: '07-12-1978',
        about: 'Пока в России 😂',
        work: 'Работа на АЗС',
    },
    {
        nickname: 'Михаил Оршанский',
        name: 'Михаил Михайлович, Миха паравоз',
        avatar: './images/modal_birthday_avatars/Mikhail_Orshansky.jpg',
        birthday_date: '21-12-1986',
        about: 'Хачу на море',
        work: 'Псих железнодорожник, люблю крутить гайки',
    },

    {
        nickname: 'ТЕСТИРОВАНИЕ ДР...',
        name: '',
        avatar: './images/modal_birthday_avatars/no_avatar.jpg',
        birthday_date: '27-11-2022',
        about: 'что-нибудь о себе...',
        work: 'чем могу быть полезен сообществу...',
    },
    {
        nickname: 'ТЕСТИРОВАНИЕ...',
        name: 'КИБЕР ПОНЕДЕЛЬНИК',
        avatar: './images/modal_birthday_avatars/cyber_monday.png',
        birthday_date: '28-11-2022',
        about: '',
        work: '',
    },
    {
        nickname: '',
        name: '',
        avatar: './images/modal_birthday_avatars/no_avatar.jpg',
        birthday_date: '',
        about: '',
        work: '',
    },
]
